@extends('layouts.app')

@push('scripts')
@vite('resources/js/payment.js')
@endpush

@section('content')
<section
    class="pt-4 pb-12 md:pt-24 md:pb-12 md:mb-12 flex flex-col md:flex-row justify-center items-center md:items-start space-y-20 md:space-y-0 md:space-x-6 lg:space-x-12 text-center md:text-left">
    <div class="w-full md:w-7/12 md:mr-8">
        <h1 class="text-5xl lg:text-6xl font-extrabold tracking-tight mb-6">
            <span>Elevate Your</span>
            <br>
            <span>Landing Pages</span>
            <br>
            <span class="inline-grid">
                <span
                    class="pointer-events-none col-start-1 row-start-1 bg-[linear-gradient(90deg,theme(colors.error)_0%,theme(colors.secondary)_9%,theme(colors.secondary)_42%,theme(colors.primary)_47%,theme(colors.accent)_100%)] bg-clip-text blur-2xl [-webkit-text-fill-color:transparent] [transform:translate3d(0,0,0)] [@supports(color:oklch(0_0_0))]:bg-[linear-gradient(90deg,oklch(var(--s))_4%,color-mix(in_oklch,oklch(var(--s)),oklch(var(--er)))_22%,oklch(var(--p))_45%,color-mix(in_oklch,oklch(var(--p)),oklch(var(--a)))_67%,oklch(var(--a))_100.2%)]"
                    aria-hidden="true">to Perfection!</span>
                <span
                    class="[&amp;::selection]:text-base-content relative col-start-1 row-start-1 bg-[linear-gradient(90deg,theme(colors.error)_0%,theme(colors.secondary)_9%,theme(colors.secondary)_42%,theme(colors.primary)_47%,theme(colors.accent)_100%)] bg-clip-text [-webkit-text-fill-color:transparent] [&amp;::selection]:bg-blue-700/20 [@supports(color:oklch(0_0_0))]:bg-[linear-gradient(90deg,oklch(var(--s))_4%,color-mix(in_oklch,oklch(var(--s)),oklch(var(--er)))_22%,oklch(var(--p))_45%,color-mix(in_oklch,oklch(var(--p)),oklch(var(--a)))_67%,oklch(var(--a))_100.2%)]">to
                    Perfection!</span>
            </span>
            <br>
        </h1>
        <p class="mb-4 text-lg opacity-90">
            Are you ready to take your landing pages to the next level? Introducing {{config('app.name')}} – your
            trusted partner in optimizing user interface, user experience, visual design, content, and SEO. We bring the
            power of artificial intelligence to revolutionize the way you craft your online presence.
        </p>
        <div class="inline-flex flex-col justify-center items-center my-5 gap-2">
            <a href="{{route('payments.create')}}" class="btn btn-primary btn-wide">Get Started Now!</a>
            <a onclick="document.getElementById('faq').scrollIntoView({ behavior: 'smooth', block: 'end' ,
                inline: 'nearest' })" class="btn btn-ghost btn-wide">How it
                works?</a>
        </div>
    </div>

    <div class="relative w-full md:w-5/12 flex flex-col justify-start items-start gap-16 md:gap-24">

    </div>
</section>

<section class="grid gap-12 md:gap-24 text-center md:text-left pb-12 md:pb-24">
    <div class="text-center">
        <h2 class="font-extrabold text-4xl md:text-5xl tracking-tight mb-4 md:mb-6">See the Magic Unfold</h2>
        <p class="md:text-lg opacity-90">Curious about what {{config('app.name')}} can do for your landing pages? Take a
            sneak peek into the power of our AI-driven analysis with these example roasts. These excerpts showcase real
            insights and recommendations generated by {{config('app.name')}}</p>
    </div>
    <div class="grid md:grid-cols-3 gap-5">
        @foreach ($payments as $payment)
        <a href="{{route('payments.show', $payment)}}"
            class="mockup-browser bg-base-200 cursor-pointer hover:opacity-30 transition-all duration-300">
            <div class="mockup-browser-toolbar">
                <div class="input">{{$payment->url}}</div>
            </div>
            <img class="max-h-72 object-cover w-full object-top" src="{{$payment->computer_image_url}}">
        </a>
        @endforeach
    </div>
</section>

<section class="max-w-4xl mx-auto" id="faq">
    <h2 class="text-3xl font-extrabold tracking-tight text-center mb-12 md:mb-24">Frequently asked questions</h2>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" checked="checked" />
        <div class="collapse-title text-xl font-medium">
            1. What is {{config('app.name')}}?
        </div>
        <div class="collapse-content">
            <p>{{config('app.name')}} is an innovative web service that utilizes artificial intelligence to analyze and
                optimize landing pages across five main categories: user interface, user experience, visual design,
                content, and SEO. We provide actionable insights to enhance the performance and effectiveness of your
                digital presence.</p>
        </div>
    </div>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" />
        <div class="collapse-title text-xl font-medium">
            2. How does {{config('app.name')}} work?
        </div>
        <div class="collapse-content">
            <p>Our AI algorithms evaluate various elements of your landing page, providing real-time feedback and
                recommendations. Simply input the URL of your landing page, and {{config('app.name')}} will generate a
                comprehensive analysis highlighting areas for improvement in user interface, experience, design,
                content, and SEO.</p>
        </div>
    </div>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" />
        <div class="collapse-title text-xl font-medium">
            3. Is {{config('app.name')}} suitable for any industry?
        </div>
        <div class="collapse-content">
            <p>Yes, {{config('app.name')}} is designed to be adaptable across diverse industries. Our personalized
                recommendations take into account the specific needs and characteristics of your industry and target
                audience.</p>
        </div>
    </div>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" />
        <div class="collapse-title text-xl font-medium">
            4. How long does it take to receive the analysis?
        </div>
        <div class="collapse-content">
            <p>You can expect to receive the initial analysis within 5 minutes after submitting your landing page URL
                and completing the payment. The real-time roasting feature allows you to witness immediate insights and
                improvements.</p>
        </div>
    </div>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" />
        <div class="collapse-title text-xl font-medium">
            5. Is my data secure when using {{config('app.name')}}?
        </div>
        <div class="collapse-content">
            <p>We take data security seriously. Your information is encrypted and handled with the utmost care. We do
                not store any sensitive data beyond the analysis period, ensuring your privacy and security.</p>
        </div>
    </div>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" />
        <div class="collapse-title text-xl font-medium">
            6. How can I get in touch with {{config('app.name')}} support?
        </div>
        <div class="collapse-content">
            <p>If you have any questions or need assistance, reach out to us via <a href="mailto:reider340@gmail.com"
                    class="text-secondary">email</a> or through our contact form.</p>
        </div>
    </div>

    <div class="collapse collapse-plus bg-base-200 mb-5">
        <input type="radio" name="my-accordion-3" />
        <div class="collapse-title text-xl font-medium">
            7. What is the cost for a {{config('app.name')}} analysis?
        </div>
        <div class="collapse-content">
            <p>Each {{config('app.name')}} analysis is priced at $9.99. This fee includes a comprehensive review of your
                landing page across five key categories: user interface, user experience, visual design, content, and
                SEO.</p>
        </div>
    </div>
</section>

<section class="card bg-primary text-primary-content w-full md:w-[32rem] mx-auto mt-10 md:mt-20">
    <div class="card-body items-center text-center gap-6">
        <h3 class="card-title">Join the {{config('app.name')}} Revolution!</h3>
        <p class="opacity-90">Don't let your landing pages fall behind. Embrace the future of digital optimization with
            {{config('app.name')}}. Your success is just a roast away!</p>
        <div class="card-actions justify-center"><a class="btn btn-wide" href="{{route('payments.create')}}">Get Started
                Now!</a></div>
    </div>
</section>
@endsection
